### ISSUE TITLE
Font Awesome の軽量化

### ISSUE THREAD

**Issue by dotwistaria** [39e/hugo-wolke#10]
使用するアイコンは数種類のみなのでそこだけ書き出し軽量化したいです

`config.toml` にオプション追加し選択できるようにするといいかも？

**Comment by 39e** [comment]
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/solid.css" integrity="sha384-wnAC7ln+XN0UKdcPvJvtqIH3jOjs9pnKnq9qX68ImXvOGz2JuFoEiCjT8jyZQX2z" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/brands.css" integrity="sha384-nT8r1Kzllf71iZl81CdFzObMsaLOhqBU1JD2+XoAALbdtWaXDOlWOZTR4v1ktjPE" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/fontawesome.css" integrity="sha384-HbmWTHay9psM8qyzEKPc8odH4DsOuzdejtnr+OFtDmOcIVnhgReQ4GZBH7uwcjf6" crossorigin="anonymous">
```

から必要なものを抽出

**Comment by 39e** [comment]
必要なものをリストアップ

フェイスブックとツイッターは `sidebar.author` と `記事ページ.SNS共有` で

## 全ページ共通
- `fas`
- `fa-calendar`
- `fa-bookmark`

### sidebar.author
- `fab`
- `fa-facebook
- `fa-twitter`
- `fa-github`

## 記事ページ
- `fa-sync`

### SNS共有
- `fab`
- `fa-facebook
- `fa-twitter`
- `fa-google-plus`
- `fa-get-pocket`
- `fa-line`

**Comment by 39e** [comment]
we

**Comment by 39e** [comment]
https://www.ampproject.org/ja/docs/design/responsive/custom_fonts

`confgi.toml` で `fontawesome = "min"` にしたら有効活用
