### ISSUE TITLE
記事ページのヘッダ内容がごちゃごちゃしてる

### ISSUE THREAD

**Issue by rgshm7jbk3lh** [39e/hugo-wolke#15]
`layouts/_default/summary.html` の `header` タグ内に同じことが書いてある

具体的にはタイトルの上にあるパンくずリストにタイトル、セクションを含んでる
タイトルはそのままでもいいと思うがタイトル下のセクション表示をタグに変更したほうがいいと思う

また、サムネイル画像の下に設置してあるがサムネイル画像の真上・サイトタイルとサムネイル画像の間のグレー部分など違う位置も検討してほしい

**Comment by 39e** [comment]
確かに内容の重複があるので後日変更します
