### ISSUE TITLE
ナビゲーションに隙間ができる

### ISSUE THREAD

**Issue by dw8uuds8v4ew** [39e/hugo-wolke#16]
共有ボタン・ページネーションを、スマホで見た場合隙間ができていて気持ち悪かったので報告

特に一番左とその次の間によく隙間ができていた

**Comment by dotwistaria** [comment]
![efe7c9b3-88fe-44ec-bf48-5b4834e7d630](https://user-images.githubusercontent.com/16688755/45069908-cbfd5780-b109-11e8-832f-0a1e03a55ea1.jpeg)
![933336b3-ed9d-4cd1-bfb0-9339d1ce1adc](https://user-images.githubusercontent.com/16688755/45069909-cc95ee00-b109-11e8-89d9-3df6766d4775.jpeg)

多分このことかな？

**Comment by 39e** [comment]
症状を確認しました。原因が分かり次第修正します！
