### ISSUE TITLE
[Feature Request] partials内のカスタムCSSがほしい

### ISSUE THREAD

**Issue by JunJi-JiaYue** [39e/hugo-wolke#6]
https://github.com/dim0627/hugo_theme_robust にはpartialsフォルダ内にcustom.cssがあり、これはpartialで読み込まれるためHugoの関数が使用できます。
wolkeにも同様にpartialで読み込まれるカスタムCSSがあると嬉しいです。

**Comment by JunJi-JiaYue** [comment]
ありがとうございます！
読み込む際の「.」が抜けていたので PR を出しました #7

**Comment by 39e** [comment]
@JunJi-JiaYue ちなみに robust では css ファイルがスペースでインデントされてましたが wolke ではタブでインデントしてます
